export const nationalities = [
    {value: "afghan", label: "Afghan"},
    {value: "albanian", label: "Albanian"},
    {value: "algerian", label: "Algerian"},
    {value: "american", label: "American"},
    {value: "andorran", label: "Andorran"},
    {value: "angolan", label: "Angolan"},
    {value: "antiguan_barbudan", label: "Antiguan/Barbudan"},
    {value: "argentine", label: "Argentine"},
    {value: "armenian", label: "Armenian"},
    {value: "australian", label: "Australian"},
    {value: "austrian", label: "Austrian"},
    {value: "azerbaijani", label: "Azerbaijani"},
    {value: "bahraini", label: "Bahraini"},
    {value: "comorian", label: "Comorian"},
    {value: "djiboutian", label: "Djiboutian"},
    {value: "egyptian", label: "Egyptian"},
    {value: "emirati", label: "Emirati"},
    {value: "iraqi", label: "Iraqi"},
    {value: "jordanian", label: "Jordanian"},
    {value: "kuwaiti", label: "Kuwaiti"},
    {value: "lebanese", label: "Lebanese"},
    {value: "libyan", label: "Libyan"},
    {value: "mauritanian", label: "Mauritanian"},
    {value: "moroccan", label: "Moroccan"},
    {value: "omani", label: "Omani"},
    {value: "palestinian", label: "Palestinian"},
    {value: "qatari", label: "Qatari"},
    {value: "saudi", label: "Saudi"},
    {value: "somali", label: "Somali"},
    {value: "sudanese", label: "Sudanese"},
    {value: "syrian", label: "Syrian"},
    {value: "tunisian", label: "Tunisian"},
    {value: "yemeni", label: "Yemeni"},
    {value: "other", label: "Other"}

];
